POST http://localhost:3000/exams
Content-Type: application/json

{
    "name": "Exame de Urina",
    "status": "active",
    "examType": "clinical analysis"
}

########

GET http://localhost:3000/exams

########

GET http://localhost:3000/exams/1


########

PUT http://localhost:3000/exams/2
Content-Type: application/json

{
    "name": "Exame Completo",
    "status": "active",
    "examType": "image"
}

########
DELETE http://localhost:3000/exams/1