version: '3.7'

services:
  main:
    build: .
    entrypoint: /entrypoint.sh
    container_name: wa-hospital-backend-main
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/home/node/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
    
  postgres:
    container_name: wa-hospital-backend-postgres
    image: postgres:13-alpine
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_DB: ${TYPEORM_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data

networks:
  webnet:
volumes:
  pgdata: