version: '2'

services:
  web:
    container_name: wahospital-api
    build: docker/dev
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - database

  database:
    container_name: wahospital-database
    image: postgres:11.5-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${TYPEORM_DATABASE}
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"